inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_fixme.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'
    - 'lib/bcl_up_server/specs/**/*'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'lib/generators/bcl_up_server/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'bcl_up_server.gemspec'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/bcl_up_server/configuration.rb'
