inherit_from:
  - .rubocop_todo.yml
  - .rubocop_fixme.yml

inherit_gem:
  bixby: bixby_default.yml



AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'
    - 'lib/bcl_up_server/specs/**/*'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'lib/generators/bcl_up_server/**/*'

Metrics/BlockLength:
  IgnoredMethods: [ 'included' ]
  Exclude:
    - 'bcl_up_server.gemspec'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/bcl_up_server/configuration.rb'
